language: bash

before_install:
  - export VERSION=$(wget -q -O - https://api.github.com/repos/hadolint/hadolint/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/hadolint/hadolint/releases/download/v${VERSION}/hadolint-Linux-x86_64 && chmod +x hadolint-Linux-x86_64

script:
  - touch ./hadolint_results.json
  - ./hadolint-Linux-x86_64
  - ./hadolint-Linux-x86_64 -f json ./Dockerfile > ./hadolint_results.json || exit 0
  - cat ./hadolint_results.json
